[build]
  command = "npm run build"
  publish = ".next"
  functions = "functions"
  name = "dirk"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[edge_functions]]
  path = "/drivetime"
  function = "drivetime"
